name: Auto GitHub Contributions

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Run Contribution Script
        run: python rodeo.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add daily_contributions.txt
          git commit -m "Automated commit on $(date)" || exit 0  # Prevent errors if no changes
          git push https://x-access-token:${GH_PAT}@github.com/ottoman9/Binary-Classification-Machine-Learning-Model.git main
